# Generated by Django 6.0 on 2025-12-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Auto generated video call link', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, help_text='Doctor notes / advice'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescription',
            field=models.FileField(blank=True, help_text='Doctor uploaded prescription PDF', null=True, upload_to='prescriptions/'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
