# Generated by Django 6.0 on 2025-12-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_meeting_link_appointment_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='prescription',
        ),
        migrations.AddField(
            model_name='appointment',
            name='advice',
            field=models.TextField(blank=True, help_text='Doctor advice'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='diagnosis',
            field=models.TextField(blank=True, help_text='Doctor diagnosis'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='medicines',
            field=models.TextField(blank=True, help_text='Medicine name, dosage, frequency'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in KG', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescription_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
